In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [2]:
df = pd.read_csv('/kaggle/input/competitions/titanic/train.csv')

In [3]:
df.head(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [4]:
print(df.groupby('Sex')['Survived'].sum())

Sex
female    233
male      109
Name: Survived, dtype: int64

**more females survived**

In [5]:
print(df.groupby('Sex')['Survived'].mean()*100)

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [6]:
import matplotlib.pyplot as plt

In [7]:
df['AgeRange'] = pd.cut(df['Age'],bins =[0,12,19,45,60,100], labels=['child','teen','adult','old','very_old'])

In [8]:
print(df.groupby('AgeRange')['Survived'].sum())
print(df.groupby('AgeRange')['Survived'].mean())

AgeRange
child        40
teen         39
adult       173
old          33
very_old      5
Name: Survived, dtype: int64
AgeRange
child       0.579710
teen        0.410526
adult       0.387025
old         0.407407
very_old    0.227273
Name: Survived, dtype: float64

/tmp/ipykernel_16/2029370968.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('AgeRange')['Survived'].sum())
/tmp/ipykernel_16/2029370968.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('AgeRange')['Survived'].mean())

In [9]:
print(df.isnull().sum())
print(df.isnull().mean()*100)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
AgeRange       177
dtype: int64
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
AgeRange       19.865320
dtype: float64

In [10]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

PassengerId: 891
Survived: 2
Pclass: 3
Name: 891
Sex: 2
Age: 88
SibSp: 7
Parch: 7
Ticket: 681
Fare: 248
Cabin: 147
Embarked: 3
AgeRange: 5

In [11]:
print(df.groupby('Parch')['Survived'].mean())

Parch
0    0.343658
1    0.550847
2    0.500000
3    0.600000
4    0.000000
5    0.200000
6    0.000000
Name: Survived, dtype: float64

In [12]:
#Extract title
df['Title'] = df['Name'].str.extract(r',\s*([^\.]+)\.')

#survival rate per title
print(df.groupby('Title')['Survived'].mean().sort_values(ascending=False))

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [13]:
df['Has_Cabin'] = df['Cabin'].notna().astype(int)

In [14]:
df.drop(columns=['PassengerId', 'Name', 'Cabin', 'AgeRange'], inplace=True)

In [15]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Title,Has_Cabin
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S,Mr,0
1,1,1,female,38.0,1,0,PC 17599,71.2833,C,Mrs,1
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,Miss,0
3,1,1,female,35.0,1,0,113803,53.1000,S,Mrs,1
4,0,3,male,35.0,0,0,373450,8.0500,S,Mr,0
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,211536,13.0000,S,Rev,0
887,1,1,female,19.0,0,0,112053,30.0000,S,Miss,1
888,0,3,female,NaN,1,2,W./C. 6607,23.4500,S,Miss,0
889,1,1,male,26.0,0,0,111369,30.0000,C,Mr,1
890,0,3,male,32.0,0,0,370376,7.7500,Q,Mr,0

In [16]:
common_titles = ['Mr', 'Miss', 'Mrs', 'Master']
df['Title'] = df['Title'].apply(lambda x: x if x in common_titles else 'Other')

print(df['Title'].value_counts())

Title
Mr        517
Miss      182
Mrs       125
Master     40
Other      27
Name: count, dtype: int64

In [17]:
df.drop(columns=['Ticket'], inplace=True)
print(df.columns.tolist())

['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Title', 'Has_Cabin']

In [18]:
#fill with S, bcoz it appeared mosttime
df['Embarked'] = df['Embarked'].fillna('S')

#fill empty age with their title group median
df['Age'] = df.groupby('Title')['Age'].transform(lambda x: x.fillna(x.median()))

In [19]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1  # +1 for the passenger themselves

# Check survival rate by family size
print(df.groupby('FamilySize')['Survived'].mean())

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

In [20]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1  # +1 for the passenger themselves

# survival rate by family size
print(df.groupby('FamilySize')['Survived'].mean())

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

In [21]:
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)

# Check
print(df['IsAlone'].value_counts())
print(df.groupby('IsAlone')['Survived'].mean())

IsAlone
1    537
0    354
Name: count, dtype: int64
IsAlone
0    0.505650
1    0.303538
Name: Survived, dtype: float64

In [22]:
df.drop(columns=['SibSp', 'Parch'], inplace=True)
print(df.columns.tolist())

['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Title', 'Has_Cabin', 'FamilySize', 'IsAlone']

In [23]:
df = df.astype({col: int for col in df.select_dtypes(bool).columns})
print(df.head())# Label encode Sex
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

# One-hot encode 
df = pd.get_dummies(df, columns=['Embarked', 'Title'], drop_first=False)

# Verify
print(df.shape)

   Survived  Pclass     Sex   Age     Fare Embarked Title  Has_Cabin  \
0         0       3    male  22.0   7.2500        S    Mr          0
1         1       1  female  38.0  71.2833        C   Mrs          1
2         1       3  female  26.0   7.9250        S  Miss          0
3         1       1  female  35.0  53.1000        S   Mrs          1
4         0       3    male  35.0   8.0500        S    Mr          0

   FamilySize  IsAlone
0           2        0
1           2        0
2           1        1
3           2        0
4           1        1
(891, 16)

In [24]:
df = df.astype({col: int for col in df.select_dtypes(bool).columns})
print(df.head())

   Survived  Pclass  Sex   Age     Fare  Has_Cabin  FamilySize  IsAlone  \
0         0       3    0  22.0   7.2500          0           2        0
1         1       1    1  38.0  71.2833          1           2        0
2         1       3    1  26.0   7.9250          0           1        1
3         1       1    1  35.0  53.1000          1           2        0
4         0       3    0  35.0   8.0500          0           1        1

   Embarked_C  Embarked_Q  Embarked_S  Title_Master  Title_Miss  Title_Mr  \
0           0           0           1             0           0         1
1           1           0           0             0           0         0
2           0           0           1             0           1         0
3           0           0           1             0           0         0
4           0           0           1             0           0         1

   Title_Mrs  Title_Other
0          0            0
1          1            0
2          0            0
3          1            0
4          0            0

**TRAIN MODEL**

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Split
X = df.drop(columns=['Survived'])
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Evaluate
y_pred = rf_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print(classification_report(y_test, y_pred))

Accuracy: 0.8436
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       105
           1       0.81      0.81      0.81        74

    accuracy                           0.84       179
   macro avg       0.84      0.84      0.84       179
weighted avg       0.84      0.84      0.84       179

In [26]:
import pandas as pd
import matplotlib.pyplot as plt

feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feature_importance)

Fare            0.240619
Age             0.212101
Sex             0.124075
Title_Mr        0.111864
Pclass          0.072721
FamilySize      0.067281
Title_Mrs       0.038212
Has_Cabin       0.034649
Title_Miss      0.032067
Embarked_S      0.015211
Embarked_C      0.014683
IsAlone         0.013859
Title_Master    0.009307
Embarked_Q      0.007509
Title_Other     0.005842
dtype: float64

In [27]:
import os

# Find all available input files
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [28]:
test_df = pd.read_csv('/kaggle/input/competitions/titanic/test.csv')
passenger_ids = test_df['PassengerId']

test_df['Title'] = test_df['Name'].str.extract(r',\s*(\w+)\.')
test_df['Title'] = test_df['Title'].apply(lambda x: x if x in ['Mr','Miss','Mrs','Master'] else 'Other')
test_df['Has_Cabin'] = test_df['Cabin'].notna().astype(int)
test_df['FamilySize'] = test_df['SibSp'] + test_df['Parch'] + 1
test_df['IsAlone'] = (test_df['FamilySize'] == 1).astype(int)
test_df.drop(columns=['PassengerId','Name','Cabin','Ticket','SibSp','Parch'], inplace=True)
test_df['Embarked'] = test_df['Embarked'].fillna('S')
test_df['Age'] = test_df.groupby('Title')['Age'].transform(lambda x: x.fillna(x.median()))
test_df['Fare'] = test_df['Fare'].fillna(test_df['Fare'].median())
test_df['Sex'] = test_df['Sex'].map({'male': 0, 'female': 1})
test_df = pd.get_dummies(test_df, columns=['Embarked','Title'], drop_first=False)
test_df = test_df.astype({col: int for col in test_df.select_dtypes(bool).columns})
test_df = test_df.reindex(columns=X.columns.tolist(), fill_value=0)

pd.DataFrame({
    'PassengerId': passenger_ids,
    'Survived': rf_model.predict(test_df)
}).to_csv('submission.csv', index=False)